name: foresee
version: 0.1
summary: A modular machine learning framework, developed by the University of Cagliari.
description: A modular machine learning framework, developed by the University of Cagliari.
parts:
  core:
    plugin: java
    source: https://fcole90@bitbucket.org/unicalabs/unica-machine-learning.git
    stage-packages:
      - openjdk-8-jdk
      - graphviz
