name: foresee
version: 0.1
summary: A modular machine learning framework, developed by the University of Cagliari.
description: A modular machine learning framework, developed by the University of Cagliari.
#icon:  A path to an icon for the package - this is optional.

apps:
  foresee:
    command: bin/foresee

parts:
  core:
    plugin: copy
    source: ../
    files:
      Linux/foresee: /bin/foresee
      foresee*.jar: /bin/foresee.jar
