name: foresee
version: 0.1
summary: A modular machine learning framework, developed by the University of Cagliari.
description: A modular machine learning framework,
 developed by the University of Cagliari.
 The project aims at reusability and extensibility of the code,
 allowing third parties to add new functionalities, yet offering
 a selected set of builtin functionalities of wide use.
icon: # A path to an icon for the package - this is optional.
