# Prepare libraries
# =================

all: junit-4.jar hamcrest.jar system-rules.jar

# Symlink to current version of junit4
junit-4.jar:
	ln -s junit-4* junit-4.jar

# Symlink to current version of hamcrest
hamcrest.jar:
	ln -s hamcrest* hamcrest.jar

# Symlink to current version of system-rules
system-rules.jar:
	ln -s system-rules* system-rules.jar
