include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/modules-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/libraries-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/modules-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/libraries-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/modules-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/libraries-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/foresee.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/utils.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/datasets-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/commandlists-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/modules-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/libraries-interfaces.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/predictions.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/tests.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core.mk
include /home/fabio/Desktop/Internship/Foresee/makefiles/core-interfaces.mk
