# Prepare libraries
# =================

test-libs: junit-4.jar hamcrest.jar

# Symlink to current version of junit4
junit-4.jar:
	ln -s junit-4* junit-4.jar

# Symlink to current version of hamcrest
hamcrest.jar:
	ln -s hamcrest* hamcrest.jar
