# Prepare libraries
# =================

all: log4j-api.jar log4j-core.jar

# Symlink to current version of log4j-api
log4j-api.jar:
	ln -s log4j-api* log4j-api.jar

# Symlink to current version of log4j-core
log4j-core.jar:
	ln -s log4j-core* log4j-core.jar
